### ISSUE TITLE
what to do

### ISSUE THREAD

**Issue by rahulbanwasi** [vinayak-7-0-3/AIO-Music-Helper#24]
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/root/AIO-Music-Helper/bot/__main__.py", line 79, in <module>
    app.run()
  File "/usr/local/lib/python3.10/dist-packages/pyrogram/methods/utilities/run.py", line 80, in run
    run(self.start())
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/root/AIO-Music-Helper/bot/__main__.py", line 64, in start
    await loadConfigs()
  File "/root/AIO-Music-Helper/bot/__main__.py", line 33, in loadConfigs
    await qobuz.login()
  File "/root/AIO-Music-Helper/bot/helpers/qobuz/handler.py", line 19, in login
    qobuz_api.login()
  File "/root/AIO-Music-Helper/bot/helpers/qobuz/qopy.py", line 223, in login
    self.get_tokens()
  File "/root/AIO-Music-Helper/bot/helpers/qobuz/qopy.py", line 217, in get_tokens
    self.id = str(bundle.get_app_id())
  File "/root/AIO-Music-Helper/bot/helpers/qobuz/bundle.py", line 48, in get_app_id
    raise NotImplementedError("Failed to match APP ID")
NotImplementedError: Failed to match APP ID

**Comment by vinayak-7-0-3** [comment]
Fixed in [v0.30](https://github.com/vinayak-7-0-3/AIO-Music-Helper/commit/ac6918292a427d8fdb4db596095d50a301a1d180)
